sudo: required
services:
  - docker

before_install:
  - docker build -t tpatel84/docker-react -f Dockerfile.dev .

script:
  - docker run tpatel84/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "react-test"
  env: "ReactTest-env"
  bucket_name: "elasticbeanstalk-us-west-2-548587940779"
  bucket_path: "react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
   